import mega from "./assets/mega_circle.svg";
import star from "./assets/star.svg";
import usa from "./assets/usa.svg";
import alarm from "./assets/alarm_blue.svg";

const cards = [
  {
    id: 0,
    imgGame: mega,
    imgStar: star,
    imgFlag: usa,
    imgClock: alarm,
    title: "MEGA MILLIONS",
    money: "$122 000 000",
    time: "1:22:01",
  },
  {
    id: 1,
    imgGame: mega,
    imgStar: star,
    imgFlag: usa,
    imgClock: alarm,
    title: "MEGA MILLIONS",
    money: "$122 000 000",
    time: "1:22:01",
  },
  {
    id: 2,
    imgGame: mega,
    imgStar: star,
    imgFlag: usa,
    imgClock: alarm,
    title: "MEGA MILLIONS",
    money: "$122 000 000",
    time: "1:22:01",
  },
  {
    id: 3,
    imgGame: mega,
    imgStar: star,
    imgFlag: usa,
    imgClock: alarm,
    title: "MEGA MILLIONS",
    money: "$122 000 000",
    time: "1:22:01",
  },
  {
    id: 4,
    imgGame: mega,
    imgStar: star,
    imgFlag: usa,
    imgClock: alarm,
    title: "MEGA MILLIONS",
    money: "$122 000 000",
    time: "1:22:01",
  },
  {
    id: 5,
    imgGame: mega,
    imgStar: star,
    imgFlag: usa,
    imgClock: alarm,
    title: "MEGA MILLIONS",
    money: "$122 000 000",
    time: "1:22:01",
  },
  {
    id: 6,
    imgGame: mega,
    imgStar: star,
    imgFlag: usa,
    imgClock: alarm,
    title: "MEGA MILLIONS",
    money: "$122 000 000",
    time: "1:22:01",
  },
  {
    id: 7,
    imgGame: mega,
    imgStar: star,
    imgFlag: usa,
    imgClock: alarm,
    title: "MEGA MILLIONS",
    money: "$122 000 000",
    time: "1:22:01",
  },
  {
    id: 8,
    imgGame: mega,
    imgStar: star,
    imgFlag: usa,
    imgClock: alarm,
    title: "MEGA MILLIONS",
    money: "$122 000 000",
    time: "1:22:01",
  },
  {
    id: 9,
    imgGame: mega,
    imgStar: star,
    imgFlag: usa,
    imgClock: alarm,
    title: "MEGA MILLIONS",
    money: "$122 000 000",
    time: "1:22:01",
  },
];

export default cards;
